version: '3.8'

services:
  # AnchorChain API (simplified - no blockchain dependency)
  anchorchain-api:
    build:
      context: .
      dockerfile: deploy/Dockerfile.api
    ports:
      - "8080:8080"
    environment:
      - API_TOKEN=demo-token
    volumes:
      - ./shared:/shared/anchor

  # Prometheus monitoring
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./deploy/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  # Grafana dashboards
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - ./deploy/grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
